### ISSUE TITLE
how can i self-host this and is it still relevant to current discord 

### ISSUE THREAD

**Issue by woss** [epswartz/DiscordEventBot#3]

**Comment by epswartz** [comment]
> is it still relevant to current discord

I wasn't sure it would be, but I just tested it out, and looks like it's still working!

As for how to self host:
1. Create a bot user on discord - Discord has guides on how to do this, the bot will need an actual bot user. Start here: https://discord.com/developers/applications/ and create a new application, then go to the bot page from the left side menu, and click Add Bot.
2. Go to the Bot page and grab its token with the copy button:
![image](https://user-images.githubusercontent.com/13987805/122119256-f6ba8580-cdf6-11eb-9e0e-4bfaaccd001c.png)
3. Grab the binary from `/bin` in this repo (darwin one is for mac OS, the other one was for Ubuntu when I made it but it'll probably work for some other flavors of linux too. I can build you a binary for a different platform but it may take me a bit to get to it.
4. Fill out a file called config.json, then run the binary. Procedure works as shown in the following screenshot (I've since invalidated the token shown, you need your own):

![image](https://user-images.githubusercontent.com/13987805/122119547-557fff00-cdf7-11eb-8d56-c3dc22a1fcf1.png)

You don't need any of the other files in the repository, you just need a config file and the binary.

5. Add the bot user to your server by going to `https://discord.com/oauth2/authorize?client_id=CLIENT_ID&scope=bot` - copy the client id from the discord app page - the id is the "Application ID" from the "General Information" page.

**Comment by epswartz** [comment]
Also, just so you know, I wrote the `Upcoming Development` section quite a while ago and have pretty much moved on - if there's any feature there that's super important to you I'll see what I can do, but no guarantees lol

**Comment by woss** [comment]
thanks a lot for this. i will test it this weekend and then report back if I encounter the errors. :)

**Comment by woss** [comment]
which command did you use to build the binary? i could spend time figuring it out too but way easier would be if you could share darwin and Linux cmds :)

**Comment by woss** [comment]
just noticed, why `bat` instead of `cat`?

**Comment by woss** [comment]
so i got it running but not working as I thought it will be. 
![image](https://user-images.githubusercontent.com/80440/122237931-005bf000-cec0-11eb-922a-2b38442cdb9a.png)

the time is in EDT which means nothing to me since I am in the EU, is the ISO time accepted?
am I missing something but it's not possible to have the card with the event and reply with the emoji?

**Comment by epswartz** [comment]
Hey again - 
1. It was `go build`, I am not sure of flags/other since it's been a long time, but you'd also have to go `go get` on some dependencies.
2. `bat` is just marginally better cat, at least for use by a human and not another script - it does coloring and autopipes to a pager if output is too long
3. EDT is eastern time, I can probably make timezone configurable relatively easily - will look some time this weekend or next week.
4. Responses are done with `!e reply <yes/no/maybe> <event name>`, e.g. `!e respond yes testevent` - not sure whether you're saying the response command is bugged, or if you want to respond by reacting to a card with an emoji (which isn't a feature the bot has).

Is that the whole chatlog? I see some usage errors for the respond command but can't see what it is that you tried to do, I just see you create the event and then get it (with respond usage errs in the middle).

**Comment by woss** [comment]
hi there,

the log is from my personal test server. and yes there are some errors that I did while typing the cmds.

It would be really nice if the users could react with the emoji instead of typing the command. most of the users on the server where I want to add this don't know how to use the commands at all. I explain them all the time how to set their TZ ( for example ) :) 

I don't speak golang that well, so unfortunately I cannot help you implement this feature and also I have no idea how complex and time-consuming implementing that would be. 

if this would be a typescript then I can help :)
